model: NeuMF
dataset: ml-100k
data_path: data/
mf_embedding_size: 64
mlp_embedding_size: 64
mlp_hidden_size:
- 128
- 64
dropout_prob: 0.5
mf_train: true
mlp_train: true
use_pretrain: false
mf_pretrain_path: null
mlp_pretrain_path: null
epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.0001
eval_step: 5
stopping_step: 5
eval_args:
  split:
    RS:
    - 0.8
    - 0.1
    - 0.1
  group_by: user
  order: RO
  mode: full
metrics:
- Recall
- MRR
- NDCG
- Hit
- Precision
topk:
- 10
valid_metric: NDCG@10
show_progress: false
checkpoint_dir: results/checkpoints
