model: SLIMElastic
dataset: ml-100k
data_path: data/
embedding_size: 64
train_neg_sample_args:
  distribution: uniform
  sample_num: 1
epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.001
eval_step: 5
stopping_step: 5
alpha: 0.1
l1_ratio: 0.001
positive_only: true
hide_item: true
eval_args:
  split:
    RS:
    - 0.8
    - 0.1
    - 0.1
  group_by: user
  order: RO
  mode: full
metrics:
- Recall
- MRR
- NDCG
- Hit
- Precision
topk:
- 10
valid_metric: NDCG@10
show_progress: false
checkpoint_dir: results/checkpoints
