model: FISM
dataset: ml-100k
data_path: data/

embedding_size: 64
train_neg_sample_args:
  distribution: uniform
  sample_num: 1

epochs: 20
train_batch_size: 2048
learner: adam
learning_rate: 0.001
eval_step: 10
stopping_step: 20

embedding_size: 64
reg_weights: [1e-2, 1e-2]

eval_args:
  split:
    RS: [0.8, 0.1, 0.1]
  group_by: user
  order: RO
  mode: full
metrics: [Recall, MRR, NDCG, Hit, Precision]
topk: [10]
valid_metric: MRR@10
